apiVersion: v1
kind: ConfigMap
metadata:
  name: hotel-config
  namespace: hotel
data:
  DB_NAME: hotel_spring
  DB_URL: jdbc:postgresql://postgres:5432/hotel_spring
  PORT: "8080"
  BACKEND_URL: http://hotel-backend:8080
  FRONTEND_ORIGIN: http://localhost:5173
  JPA_SHOW_SQL: "false"
  SESSION_TIMEOUT: 30m
  SHUTDOWN_TIMEOUT: 20s
